plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.moneyco"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        useIR = true
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_version
        kotlinCompilerVersion '1.5.31'
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.4.0'
    implementation 'androidx.activity:activity-compose:1.4.0'

    // Pour ViewModel
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.4.0")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2")

    // Dépendance Navigation pour jetpack compose
    implementation "androidx.navigation:navigation-compose:2.4.0-beta02"

    // Dépendance 'Lottie files' pour les animations dans jetpack compose
    implementation "com.airbnb.android:lottie-compose:$lottieVersion"

    // Dépendance Material Icons pour jetpack compose
    implementation "androidx.compose.material:material-icons-extended:$compose_version"

    // Dépendance pour SplashScreen
    implementation 'androidx.core:core-splashscreen:1.0.0-alpha01'

    // Room
    implementation "androidx.room:room-runtime:2.4.0"
    kapt "androidx.room:room-compiler:2.4.0"
    implementation "androidx.room:room-ktx:2.4.0"

    // Hilt for Dependency Injection
    implementation "com.google.dagger:hilt-android:2.40"
    kapt "com.google.dagger:hilt-android-compiler:2.40"
    implementation "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"

    // Encrypted Shared Preferences
    implementation "androidx.security:security-crypto:1.1.0-alpha03"

    //Une bibliothèque de chargement d'images pour Android soutenue par Kotlin Coroutines
    implementation("io.coil-kt:coil-compose:1.4.0")

    // Une bibliothèque qui fournit un modèle UX de balayage pour
    // rafraîchir, similaire au SwipeRefreshLayout d'Android.
    implementation 'com.google.accompanist:accompanist-swiperefresh:0.19.0'

    // Dépendance pour les graphiques sur Jetpack Compose
    implementation 'com.github.tehras.charts:pie:beta-01'
    implementation 'com.github.tehras.charts:line:beta-01'

    implementation("ma.hu:compose-charts:0.3.2")

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"

}